# Generated by Django 4.1.4 on 2023-01-23 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('currency', models.CharField(choices=[('KZT', 'Тенге'), ('EURO', 'Евро'), ('USD', 'Доллар')], default='KZT', max_length=6, verbose_name='Валюта')),
                ('capture_method', models.CharField(choices=[('AUTO', 'Автоматический платеж'), ('MANUAL', 'Двухстадийный платеж')], default='AUTO', max_length=10, verbose_name='Способ списания платежа')),
                ('external_id', models.CharField(max_length=100, verbose_name='Внешний идентификатор заказа')),
                ('description', models.CharField(max_length=255, verbose_name='Описание заказа')),
                ('mcc', models.CharField(blank=True, max_length=4, null=True, verbose_name='MCC Код')),
                ('extra_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дополнительные данные, связанные с заказом')),
                ('attempts', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='Количество попыток оплаты')),
                ('customer_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Идентификатор плательщика')),
                ('backref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Checkout url')),
                ('order_status', models.CharField(choices=[('UNPAID', 'Не оплачено'), ('HOLD', 'Холдированный'), ('PAID', 'Оплачено')], default='UNPAID', max_length=6, verbose_name='Статус заявки')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='legal_entity.legalentity')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ('-created_at',),
            },
        ),
    ]
