# Generated by Django 4.1.4 on 2023-01-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование банка')),
                ('bin', models.CharField(max_length=22, verbose_name='БИН')),
                ('bik', models.CharField(max_length=22, verbose_name='БИК')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Список банков',
                'db_table': 'bank',
                'ordering': ('-created_at',),
            },
        ),
    ]
