# Generated by Django 4.1.4 on 2023-01-23 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal_entity', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('total_amount', models.IntegerField(verbose_name='Общая сумма заявки, включая коммисии')),
                ('reversed_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата сторнирования')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (причина отклонения, описание ошибки, причинасторно)')),
                ('original_bid_id', models.IntegerField(blank=True, null=True, verbose_name='ID исходной заявки (для заявок “Сторно”)')),
                ('receiver_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tелефон получателя')),
                ('api_id', models.CharField(blank=True, max_length=22, null=True, verbose_name='API с которого была созадана заявка')),
                ('fee_merchant_sent', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма комиссии, списанная с Мерчанта')),
                ('fee_merchant_received', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма комиссии, полученная Мерчантом')),
                ('bid_finance_status', models.CharField(choices=[('CAPTURED', 'Зарегистрированная'), ('APPROVED', 'Одобренный'), ('PROCESSING', 'В обработке'), ('FAILED', 'Неуспешный'), ('CANCELLED', 'Отмененный'), ('REFUNDED', 'Возврат')], default='PROCESSING', max_length=20, verbose_name='Статус операция')),
                ('bid_finance_type', models.CharField(choices=[('PAYMENT', 'Платеж'), ('TRANSFER', 'Перевод')], max_length=20, verbose_name='Тип финансовой операции')),
                ('currency', models.CharField(choices=[('KZT', 'Тенге'), ('EURO', 'Евро'), ('USD', 'Доллар')], default='KZT', max_length=6, verbose_name='Валюта')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal_entity.legalentity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bid_finances', to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Финансовая операция',
                'verbose_name_plural': 'Финансовые операции',
                'db_table': 'bid_finance',
                'ordering': ('-created_at',),
                'index_together': {('uuid',)},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('html_template', models.TextField(verbose_name='Шаблон формы оплаты')),
                ('bid_finance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template', to='bid_finance.bidfinance', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'db_table': 'templates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BidFinanceTye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('system_name', models.CharField(max_length=100, verbose_name='Имя внутри системы')),
                ('display_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип финансовых операция',
                'verbose_name_plural': 'Тип финансовых операции',
                'db_table': 'bid_finance_type',
                'ordering': ('-created_at',),
                'unique_together': {('system_name', 'display_name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('amount', models.IntegerField(verbose_name='сумма')),
                ('currency', models.CharField(choices=[('KZT', 'Тенге'), ('EURO', 'Евро'), ('USD', 'Доллар')], default='KZT', max_length=6, verbose_name='Валюта')),
                ('transaction_status', models.CharField(choices=[('SUCCEEDED', 'Успешный'), ('PROCESSING', 'В обработке'), ('FAILED', 'Неуспешный')], max_length=10, verbose_name='Статус транзакции')),
                ('transaction_type', models.CharField(choices=[('AUTO', 'Автоматический'), ('HOLDING', 'Холдированный'), ('CANCEL', 'Отменённый '), ('REFUND', 'Возврат')], default='AUTO', max_length=10, verbose_name='Тип транзакции')),
                ('sender_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tелефон отправителя')),
                ('receiver_phone', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tелефон получателяы')),
                ('is_fee', models.BooleanField(default=False, verbose_name='Kомиссионая транзакция')),
                ('is_reversal', models.BooleanField(default=False, verbose_name='Tранзакция сторнирования')),
                ('bid_finance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='bid_finance.bidfinance', verbose_name='ID фин. заявки')),
            ],
            options={
                'verbose_name': 'Tранзакции по фин. операции',
                'verbose_name_plural': 'Tранзакции по фин. операции',
                'db_table': 'transaction',
                'ordering': ('-created_at',),
                'index_together': {('bid_finance',)},
            },
        ),
    ]
