# Generated by Django 4.1.4 on 2023-01-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INIT_PAYMENT', 'Init Payment'), ('APPROVE', 'Approve'), ('CAPTURE', 'Capture'), ('CANCEL', 'Cancel'), ('REFUND', 'Refund'), ('FINISH_3D_SECURE', 'Finish 3D Secure'), ('GET_STATUS', 'Get Status')], default='INIT_PAYMENT', max_length=30, verbose_name='Тип транзакции'),
        ),
    ]
