# Generated by Django 4.1.4 on 2023-01-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid_finance', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='html_template',
        ),
        migrations.AddField(
            model_name='template',
            name='origin_template',
            field=models.TextField(blank=True, null=True, verbose_name='Шаблон формы оплаты'),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_template',
            field=models.TextField(blank=True, null=True, verbose_name='Шаблон формы оплаты'),
        ),
    ]
