apiVersion: v1
kind: Service
metadata:
  name: crm-backend
  labels:
    app: crm-backend 
spec:
  ports:
  - name: http
    port: 8010
    targetPort: 8010
  selector:
    app: crm-backend
  type: LoadBalancer
