# Generated by Django 4.1.4 on 2023-01-23 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('bin', models.CharField(max_length=22, unique=True, verbose_name='БИН')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('editor_id', models.IntegerField(blank=True, null=True, verbose_name='Изменил данные')),
                ('kbe', models.CharField(blank=True, max_length=4, null=True, verbose_name='KBE - 2 символа')),
                ('fee_withdraw_percent', models.CharField(blank=True, max_length=4, null=True, verbose_name='Комиссия для операцию в процентах')),
            ],
            options={
                'verbose_name': 'Мерчант',
                'verbose_name_plural': 'Мерчанты',
                'db_table': 'legal_entity',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LegalEntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('system_name', models.CharField(max_length=100, verbose_name='Имя внутри системы')),
                ('display_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тип юр.лиц',
                'verbose_name_plural': 'Тип юр.лиц',
                'db_table': 'legal_entity_type',
                'ordering': ('-created_at',),
                'unique_together': {('system_name', 'display_name')},
            },
        ),
        migrations.CreateModel(
            name='LegalEntityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('terminal', models.CharField(max_length=100, verbose_name='Терминал')),
                ('merchant_name', models.CharField(max_length=255, verbose_name='Название мерчанта')),
                ('merchant_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Мерчант url')),
                ('notify_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Мерчант notify url')),
                ('merchant_gtm', models.CharField(blank=True, max_length=255, null=True, verbose_name='GTM+')),
                ('nonce', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nonce')),
                ('p_sign', models.CharField(blank=True, max_length=255, null=True, verbose_name='P_SIGN')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal_entity.legalentity', verbose_name='Юр.лицо')),
            ],
            options={
                'verbose_name': 'Конфиг мерчанта',
                'verbose_name_plural': 'Конфиги мерчанта',
                'db_table': 'legal_entity_config',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='legalentity',
            name='legal_entity_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core', to='legal_entity.legalentityconfig', verbose_name='Конфиг'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='legal_entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type', to='legal_entity.legalentitytype', verbose_name='Тип юр.лиц'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='legalentity',
            unique_together={('bin', 'email')},
        ),
    ]
